/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmnav.ui;

import jmnav.PlaneState;

/**
 *
 * @author Jesper
 */
public class jMNAVStatusFrame extends javax.swing.JFrame {

    /**
     * Creates new form jMNAVStatusFrame
     */
    public jMNAVStatusFrame() {
        initComponents();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jMNAVStatusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jMNAVStatusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jMNAVStatusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jMNAVStatusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPane1 = new javax.swing.JTextPane();
        altMeter = new jmnav.ui.AltMeter();
        horizon1 = new jmnav.ui.Horizon();
        compass1 = new jmnav.ui.Compass();
        spdMeter1 = new jmnav.ui.SpdMeter();
        aoAMeter1 = new jmnav.ui.AoAMeter();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setText("Hello, World!");
        getContentPane().add(jTextPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 498, 198));
        getContentPane().add(altMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, 100));
        getContentPane().add(horizon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 100));
        getContentPane().add(compass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, 100));
        getContentPane().add(spdMeter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 201, 50, 100));
        getContentPane().add(aoAMeter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 201, 50, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateText(String str) {
        jTextPane1.setText(str);
    }

    public void updateState(PlaneState state) {
        altMeter.update(state);
        spdMeter1.update(state);
        horizon1.update(state);
        compass1.update(state);
        aoAMeter1.update(state);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jmnav.ui.AltMeter altMeter;
    private jmnav.ui.AoAMeter aoAMeter1;
    private jmnav.ui.Compass compass1;
    private jmnav.ui.Horizon horizon1;
    private javax.swing.JTextPane jTextPane1;
    private jmnav.ui.SpdMeter spdMeter1;
    // End of variables declaration//GEN-END:variables
}
